version: '2.1'

services:
  bigchaindb_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - bigchaindb
  mongodb:
    image: mongo:3.6
    # ports:
    #   - "27017:27017"
    command: mongod
  bigchaindb:
    depends_on:
      - mongodb
      - tendermint
    image: bigchaindb/bigchaindb:2.0.0-alpha6
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 46657
    # ports:
    #   - "9984:9984"
    #   - "9985:9985"
    #   - "46658"
  tendermint:
    image: tendermint/tendermint:0.19.9
    # volumes:
    #   - ./tmdata:/tendermint
    entrypoint: ''
    # ports:
    #   - "46656:46656"
    #   - "46657:46657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:46658"
